# 6-е домашнее задание - Библиотека numpy

ПВозможности и основные методы библиотеки numpy: http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


# Иванова Елизавета Дмитриевна НПМбд-01-19

In [1]:
import numpy as np

1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [2]:
np.linspace(-1.3, 2.5, 64)

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [7]:
n = int(input('Введите n: '))
np.array([1,2,3]*n)

Введите n: 5


array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [10]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [20]:
np.pad(np.zeros((10, 10)), pad_width=1, constant_values=1)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [26]:
A = np.ones((8,8))

A[::2,1::2] = 0
A[1::2,::2] = 0

print(A)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [30]:
def func1(n):
    
    A = np.zeros((n, n))
    
    for i in range(n):
        for j in range(n):
            
            A[i][j] = i + j
    
    return A

func1(10)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.],
       [ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.],
       [ 9., 10., 11., 12., 13., 14., 15., 16., 17., 18.]])

In [41]:
def func2(n):
    
    B = np.arange(0, n**2).reshape((n, n))
    
    B = B // n + B % n
    
    return B

func2(10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]], dtype=int32)

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [44]:
a = np.arange(1, 10, 3)
b = np.arange(11, 20, 3)

A = np.arange(1, 13).reshape((3, 4))
B = np.arange(11, 23).reshape((4, 3))

print(a.dot(b), '\n')
print(a.dot(A), '\n')
print(A.dot(B), '\n')

186 

[ 84  96 108 120] 

[[170 180 190]
 [418 444 470]
 [666 708 750]] 



8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [49]:
A = np.arange(0, 1, 0.05)

A_sin = np.sin(A)
A_cos = np.cos(A)

print(np.vstack((A_sin, A_cos)))

[[0.         0.04997917 0.09983342 0.14943813 0.19866933 0.24740396
  0.29552021 0.34289781 0.38941834 0.43496553 0.47942554 0.52268723
  0.56464247 0.60518641 0.64421769 0.68163876 0.71735609 0.75128041
  0.78332691 0.8134155 ]
 [1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
  0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
  0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
  0.62160997 0.58168309]]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [55]:
min = -1
max = 3

(max - min) * np.random.rand(3,5) + min

array([[ 0.76589466, -0.2294624 , -0.30735103,  2.05243059,  1.50199323],
       [-0.79665663,  2.30682338,  1.35290608, -0.4585481 ,  0.3420025 ],
       [ 1.83695392,  2.9108918 ,  1.31299458, -0.47651451,  1.41300015]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [69]:
A = np.arange(1, 13).reshape(3,4)

print('Матрица:\n', A)
print('Сумма всех элементов:', np.sum(A, axis=None))
print('Сумма внутри строк:', np.sum(A, axis = 1))
print('Сумма внутри столбцов:', np.sum(A, axis = 0))
print('Среднее значение:', np.mean(A, axis = 1))
print('Дисперсия:', np.var(A, axis = 1))
print('Стандартное отклонение:', np.std(A, axis=1))

Матрица:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Сумма всех элементов: 78
Сумма внутри строк: [10 26 42]
Сумма внутри столбцов: [15 18 21 24]
Среднее значение: [ 2.5  6.5 10.5]
Дисперсия: [1.25 1.25 1.25]
Стандартное отклонение: [1.11803399 1.11803399 1.11803399]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [80]:
A = np.arange(1, 13).reshape(3,4)

n = np.mean(A, axis = 1)
m = np.std(A, axis=1)

print((A - n.reshape(len(n), 1)) / m.reshape(len(m), 1))

[[-1.34164079 -0.4472136   0.4472136   1.34164079]
 [-1.34164079 -0.4472136   0.4472136   1.34164079]
 [-1.34164079 -0.4472136   0.4472136   1.34164079]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [85]:
A = np.random.random((3,3))
print(A)

print(A[np.argsort(A[:, 2])])

[[0.80344271 0.22412998 0.80177188]
 [0.85886227 0.0427898  0.1061428 ]
 [0.28769075 0.2857824  0.24917787]]
[[0.85886227 0.0427898  0.1061428 ]
 [0.28769075 0.2857824  0.24917787]
 [0.80344271 0.22412998 0.80177188]]


13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [94]:
A = np.arange(5, 25).reshape(4,5)
print('A:\n', A, '\nРазмер:', A.shape)

B = A.T @ A
C = A @ A.T

print('\nB:\n', B, '\nРазмер:', B.shape)
print('\nC:\n', C, '\nРазмер:', C.shape)

A:
 [[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 
Размер: (4, 5)

B:
 [[ 750  800  850  900  950]
 [ 800  854  908  962 1016]
 [ 850  908  966 1024 1082]
 [ 900  962 1024 1086 1148]
 [ 950 1016 1082 1148 1214]] 
Размер: (5, 5)

C:
 [[ 255  430  605  780]
 [ 430  730 1030 1330]
 [ 605 1030 1455 1880]
 [ 780 1330 1880 2430]] 
Размер: (4, 4)


Сходство: матрицы квадратные.
Отличие: размер B зависит от количества столбцов, размер С - от количества строк исходной матрицы

14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [97]:
print('Сумма диагональных элементов матрицы B:', np.trace(B))
print('Сумма диагональных элементов матрицы C:', np.trace(C))

Сумма диагональных элементов матрицы B: 4870
Сумма диагональных элементов матрицы C: 4870


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [112]:
A_rank = np.linalg.matrix_rank(A)

if A.shape[0] != A.shape[1]:
    print('Определитель и спектр матрицы B не определены, так как матрица не квадратная', 
          '\nРанг А: ', A_rank)
else:
    A_det = np.linalg.det(A)
    print('Определитель А: ', A_det, '\nРанг А: ', A_rank)


B_rank = np.linalg.matrix_rank(B)
B_det = np.linalg.det(B)
B_spectrum = np.linalg.eig(B)
   
if B.shape[0] != B.shape[1]:
    print('Определитель и спектр матрицы B не определены, так как матрица не квадратная\n', 
          '\nРанг B: ', B_rank)
else:
    print('\nОпределитель B: ', np.round(B_det, 2), '\nРанг B: ', B_rank, '\nСпектр B: ', *B_spectrum )


C_rank = np.linalg.matrix_rank(C)
C_det = np.linalg.det(C)
C_spectrum = np.linalg.eig(C)

if C.shape[0] != C.shape[1]:
    print('Определитель и спектр матрицы C не определены, так как матрица не квадратная\n',
          '\nРанг C: ', C_rank)
else:
    print('\nОпределитель C: ', np.round(C_det, 2), '\nРанг C: ', C_rank, '\nСпектр С: ', *C_spectrum)

Определитель и спектр матрицы B не определены, так как матрица не квадратная 
Ранг А:  2

Определитель B:  0.0 
Ранг B:  2 
Спектр B:  [ 4.86486111e+03  5.13889286e+00  2.49013057e-13 -1.97209705e-13
  6.75758659e-15] [[-3.92039974e-01 -6.68060371e-01 -6.32455532e-01 -3.54345052e-02
   1.18196326e-01]
 [-4.18823322e-01 -3.52968872e-01  6.32455532e-01  3.39540176e-01
  -6.69729086e-02]
 [-4.45606670e-01 -3.78773741e-02  3.16227766e-01 -4.89862917e-02
  -5.26630308e-01]
 [-4.72390018e-01  2.77214124e-01  3.38549338e-14 -7.78909925e-01
   7.81394038e-01]
 [-4.99173366e-01  5.92305622e-01 -3.16227766e-01  5.23790546e-01
  -3.05987147e-01]]

Определитель C:  -0.0 
Ранг C:  2 
Спектр С:  [ 4.86486111e+03  5.13889286e+00 -2.71585562e-13  1.76140166e-13] [[-0.22744653  0.80515097  0.51790197  0.1147862 ]
 [-0.38716549  0.38743114 -0.55766686 -0.55223085]
 [-0.54688444 -0.03028869 -0.43837218  0.76010311]
 [-0.7066034  -0.44800852  0.47813707 -0.32265846]]


У матриц А, В, С одинаковый ранг, собственные значения матриц В и С совпадают

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>

In [113]:
np.random.seed(1032196008)
np.random.randint(10)

9

## Аналитическое решение:

$\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ = $ \frac{1}{2} \int {\frac{{t - 2}}{{t}}dt}$ = $ \frac{1}{2} \int {1 - {\frac{{2}}{{t}}}dt}$ = $ \frac{1}{2}({t} - {2 \ln {\mid {t} \mid}})$ = $ (\frac{1}{2}({2x + 1} - {2 \ln {\mid {2x + 1} \mid}})) \mid_0^2 $ = $ ({x} + \frac{1}{2} - \ln {\mid {2x + 1} \mid}) \mid_0^2 $ = $ 2 - \ln {5} \approx  0.3905620875658996 $

In [162]:
# Подынтегральное выражение (функция)

def integrand(x):
    
    return (2 * x - 1) / (2 * x + 1)

In [173]:
# Метод прямоугольников

def rectangle(function, a, b, step_int):
    
    dx = (b - a) / step_int
    A = np.linspace(a, b - step_int, int(dx)) # возвращает равномерно распределенные числа из указанного интервала
    f = integrand(A) * step_int
    
    return np.sum(f)

In [182]:
# Метод трапеций

def trapezium(function, a, b, step_int):
    
    dx = (b - a) / step_int
    A = np.linspace(a, b, int(dx) + 1)
    f = integrand(A)
    
    return step_int / 2 * (f[0] + 2 * np.sum(f[1 : len(A) - 1]) + f[-1])

In [188]:
# Правило Симпсона

def Simpson(function, a, b, step_int):
    
    dx = (b - a) / step_int
    A = np.linspace(a, b, int(dx) + 1)
    N = len(A) - 1
    f = integrand(A)
    
    return step_int / 3 * (f[0] + 2 * np.sum(f[2 : N : 2])  + 4 * np.sum(f[1 : N : 2]) + f[N])

In [202]:
print('Метод прямоугольников, шаг интегрирования = 0.1: ', rectangle(integrand, 0, 2, 0.1))
print('Метод трапеций, шаг интегрирования = 0.1:        ', trapezium(integrand, 0, 2, 0.1))
print('Метод Симпсона, шаг интегрирования = 0.1:        ', Simpson(integrand, 0, 2, 0.1))

print('\nМетод прямоугольников, шаг интегрирования = 0.01: ', rectangle(integrand, 0, 2, 0.01))
print('Метод трапеций, шаг интегрирования = 0.01:        ', trapezium(integrand, 0, 2, 0.01))
print('Метод Симпсона, шаг интегрирования = 0.01:        ', Simpson(integrand, 0, 2, 0.01))

print('\nМетод прямоугольников, шаг интегрирования = 0.001: ', rectangle(integrand, 0, 2, 0.001))
print('Метод трапеций, шаг интегрирования = 0.001:        ', trapezium(integrand, 0, 2, 0.001))
print('Метод Симпсона, шаг интегрирования = 0.001:        ', Simpson(integrand, 0, 2, 0.001))

print('\nМетод прямоугольников, шаг интегрирования = 0.0001: ', rectangle(integrand, 0, 2, 0.0001))
print('Метод трапеций, шаг интегрирования = 0.0001:        ', trapezium(integrand, 0, 2, 0.0001))
print('Метод Симпсона, шаг интегрирования = 0.0001:        ', Simpson(integrand, 0, 2, 0.0001))

print('\nМетод прямоугольников, шаг интегрирования = 0.00001: ', rectangle(integrand, 0, 2, 0.00001))
print('Метод трапеций, шаг интегрирования = 0.00001:        ', trapezium(integrand, 0, 2, 0.00001))
print('Метод Симпсона, шаг интегрирования = 0.00001:        ', Simpson(integrand, 0, 2, 0.00001))

print('\nМетод прямоугольников, шаг интегрирования = 0.000001: ', rectangle(integrand, 0, 2, 0.000001))
print('Метод трапеций, шаг интегрирования = 0.000001:        ', trapezium(integrand, 0, 2, 0.000001))
print('Метод Симпсона, шаг интегрирования = 0.000001:        ', Simpson(integrand, 0, 2, 0.000001))

print('\nМетод прямоугольников, шаг интегрирования = 0.0000001: ', rectangle(integrand, 0, 2, 0.0000001))
print('Метод трапеций, шаг интегрирования = 0.0000001:        ', trapezium(integrand, 0, 2, 0.0000001))
print('Метод Симпсона, шаг интегрирования = 0.0000001:        ', Simpson(integrand, 0, 2, 0.0000001))

Метод прямоугольников, шаг интегрирования = 0.1:  0.3073751555798264
Метод трапеций, шаг интегрирования = 0.1:         0.3873751555798265
Метод Симпсона, шаг интегрирования = 0.1:         0.3905132109829916

Метод прямоугольников, шаг интегрирования = 0.01:  0.3825300888968459
Метод трапеций, шаг интегрирования = 0.01:         0.39053008889684576
Метод Симпсона, шаг интегрирования = 0.01:         0.3905620822461698

Метод прямоугольников, шаг интегрирования = 0.001:  0.38976176756603276
Метод трапеций, шаг интегрирования = 0.001:         0.3905617675660328
Метод Симпсона, шаг интегрирования = 0.001:         0.3905620875653672

Метод прямоугольников, шаг интегрирования = 0.0001:  0.3904820843658997
Метод трапеций, шаг интегрирования = 0.0001:         0.39056208436589973
Метод Симпсона, шаг интегрирования = 0.0001:         0.3905620875658996

Метод прямоугольников, шаг интегрирования = 0.00001:  0.39055213474369765
Метод трапеций, шаг интегрирования = 0.00001:         0.3905601347234616


Метод Симсона требует меньше разбиений, чем метод трапеций и прямоугольников. Метод трапеций требует меньше разбиений, чем метод прямоугольников. Также, неутрудно заметить, что метод Симпсона более точный, ближе к аналитическому решению