In [1]:
import numpy as np

In [2]:
def LU_decomposition(A):

    n = A.shape[0]
    
    L = np.identity(n)
    U = A.copy()
    
    for i in range(n):
            
        multiplier = U[i + 1 :, i] / U[i, i]
        L[i + 1 :, i] += multiplier
        multiplier.resize(multiplier.size, 1)
        U[i + 1 :] -= multiplier * U[i]
        
    return L, U

In [3]:
A = np.array([[10, 20, 30.], 
              [0, -50, 60.], 
              [70, 80, 90.]])

In [4]:
LU_decomposition(A)

(array([[1. , 0. , 0. ],
        [0. , 1. , 0. ],
        [7. , 1.2, 1. ]]),
 array([[  10.,   20.,   30.],
        [   0.,  -50.,   60.],
        [   0.,    0., -192.]]))

In [5]:
L, U = LU_decomposition(A)

In [6]:
A == L.dot(U)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
def SLAE_LU(A, x):
    
    L, U = LU_decomposition(A)
    
    L_inverse = np.linalg.inv(L)
    U_inverse = np.linalg.inv(U)
    
    a = np.array(L_inverse.dot(x))
    b = np.array(U_inverse.dot(a))
    
    return np.round(b, 2)

In [8]:
x = np.array([[30], 
              [20], 
              [10]])

In [9]:
SLAE_LU(A, x)

array([[-2.5 ],
       [ 1.  ],
       [ 1.17]])

In [10]:
np.round(np.linalg.solve(A, x), 2)

array([[-2.5 ],
       [ 1.  ],
       [ 1.17]])

In [11]:
from scipy.linalg import lu_factor, lu_solve

np.round(lu_solve(lu_factor(A), x), 2)

array([[-2.5 ],
       [ 1.  ],
       [ 1.17]])

In [12]:
def swap_rows(A, a, b):
    
    t = np.copy(A[a])
    A[a] = A[b]
    A[b] = t

In [13]:
def swap_cols(A, a, b):
    A = np.transpose(A)
    A = swap_rows(A, a, b)
    return np.transpose(A)

In [14]:
def LUP_decomposition(A):
    
    n = A.shape[0]
    
    L = np.identity(n)
    U = np.copy(A)
    P = np.identity(n)
    
    for a in range(n):
        
        b = a + 1
        
        while U[a][a] == 0:
            
            swap_rows(U, a, b)
            swap_rows(P, a, b)
            swap_rows(L, a, b)
            swap_cols(L, a, b)
            
            b += 1
        
        multiplier = U[a + 1 :, a] / U[a, a]
        L[a + 1 :, a] += multiplier
        multiplier.resize(multiplier.size, 1)
        U[a + 1 :] -= multiplier * U[a]
        
    return L, U, P

In [15]:
LUP_decomposition(A)

(array([[1. , 0. , 0. ],
        [0. , 1. , 0. ],
        [7. , 1.2, 1. ]]),
 array([[  10.,   20.,   30.],
        [   0.,  -50.,   60.],
        [   0.,    0., -192.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [16]:
L, U, P = LUP_decomposition(A)

In [17]:
A == P.dot(L.dot(U))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
P.dot(A) == L.dot(U)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [19]:
def SLAE_LUP(A, x):
    
    L, U, P = LUP_decomposition(A)
    x = P.dot(x)
    
    L_inverse = np.linalg.inv(L)
    U_inverse = np.linalg.inv(U)
    
    a = np.array(L_inverse.dot(x))
    b = np.array(U_inverse.dot(a))
    
    return np.round(b, 2)

In [20]:
SLAE_LUP(A, x)

array([[-2.5 ],
       [ 1.  ],
       [ 1.17]])

In [21]:
np.round(np.linalg.solve(A, x), 2)

array([[-2.5 ],
       [ 1.  ],
       [ 1.17]])

In [22]:
np.round(lu_solve(lu_factor(A), x), 2)

array([[-2.5 ],
       [ 1.  ],
       [ 1.17]])

In [23]:
swap_rows(A, 0, 1)

In [24]:
LU_decomposition(A)

<ipython-input-2-06b542031aa0>:10: RuntimeWarning: divide by zero encountered in true_divide
  multiplier = U[i + 1 :, i] / U[i, i]
<ipython-input-2-06b542031aa0>:13: RuntimeWarning: invalid value encountered in multiply
  U[i + 1 :] -= multiplier * U[i]
<ipython-input-2-06b542031aa0>:10: RuntimeWarning: invalid value encountered in true_divide
  multiplier = U[i + 1 :, i] / U[i, i]


(array([[ 1.,  0.,  0.],
        [inf,  1.,  0.],
        [inf, nan,  1.]]),
 array([[  0., -50.,  60.],
        [ nan,  inf, -inf],
        [ nan,  nan,  nan]]))

In [25]:
LUP_decomposition(A)

(array([[1. , 0. , 0. ],
        [0. , 1. , 0. ],
        [7. , 1.2, 1. ]]),
 array([[  10.,   20.,   30.],
        [   0.,  -50.,   60.],
        [   0.,    0., -192.]]),
 array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]]))

In [26]:
A = np.array([[10, 20, 30.], 
              [0, -50, 60.], 
              [70, 80, 90.]])
x = np.array([[30], 
              [20], 
              [10]])

In [27]:
%timeit SLAE_LU(A, x)

108 µs ± 4.37 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [28]:
%timeit SLAE_LUP(A, x)

136 µs ± 10.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
